import type { Metadata } from "next";
import { Geist_Mono, Inter, Playwrite_AU_SA } from "next/font/google";
import "./styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const playwrite = Playwrite_AU_SA({
  variable: "--font-playwrite",
  // subsets: ["latin"],
  display: "swap",
  // weight: ["100", "200", "300", "400"],
 
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playwrite.variable} ${geistMono.variable} antialiased font-inter dark`}
      >
        {children}
      </body>
    </html>
  );
}
